import 'package:meta/meta.dart';

/// Immutable data structure representing a message with metadata.
/// Use [MessageBuilder] to construct instances.
@immutable
class Message {
  /// Unique identifier (UUID) generated by the client.
  final String id;

  /// Logical type of the message (e.g., 'note'), set by the client.
  final String kind;

  /// Identifier of the sender (e.g., user ID), set by the client.
  final String source;

  /// Target recipient (e.g., group/123), set by the client.
  final String destination;

  /// Logical stream/grouping identifier (e.g., project/topic path).
  final String keyId;

  /// Optional device-specific or temporary local reference.
  final String? localKeyId;

  /// The message content or a reference to external data.
  final String value;

  /// Client-generated version UUID for ordering and deduplication.
  final String version;

  /// Optional content checksum (must be computed or verified by server).
  final String? integrityHash;

  /// Optional byte size of the content (computed on server if applicable).
  final int? size;

  /// Optional MIME type (e.g., 'text/plain', 'image/png').
  final String? contentType;

  /// Optional metadata flags (e.g., 'pinned', 'archived').
  final List<String>? flags;

  /// Monotonic sequence within a logical group. Set by the server.
  final int? sequence;

  /// UTC timestamp when the message was created (client clock).
  final DateTime created;

  /// Version of the originating application.
  final String applicationVersion;

  /// Global position across all message streams. Set by the server.
  final int? position;

  /// Optional ISO language code for the value content.
  final String? language;

  const Message._({
    required this.id,
    required this.kind,
    required this.source,
    required this.destination,
    required this.keyId,
    this.localKeyId,
    required this.value,
    required this.version,
    this.integrityHash,
    this.size,
    this.contentType,
    this.flags,
    this.sequence,
    required this.created,
    required this.applicationVersion,
    this.position,
    this.language,
  });
}

/// Builder class for constructing immutable [Message] instances.
///
/// All required fields must be set before calling [build].
///
/// Usage:
/// ```dart
/// final message = MessageBuilder()
///   .setId('uuid')
///   .setKind('note')
///   .setSource('user')
///   .setDestination('group/123')
///   .setKeyId('project/uuid/topic/uuid/title')
///   .setValue('Hello World')
///   .setVersion('ver-uuid')
///   .setSequence(1)
///   .setCreated(DateTime.utc(2025, 9, 24))
///   .setApplicationVersion('1.0.0')
///   .setPosition(100)
///   .setLanguage('en')
///   .build();
/// ```
class MessageBuilder {
  String? _id;
  String? _kind;
  String? _source;
  String? _destination;
  String? _keyId;
  String? _localKeyId;
  String? _value;
  String? _version;
  String? _integrityHash;
  int? _size;
  String? _contentType;
  List<String>? _flags;
  int? _sequence;
  DateTime? _created;
  String? _applicationVersion;
  int? _position;
  String? _language;

  // --- Setters ---

  MessageBuilder setId(String id) => _with(() => _id = id);
  MessageBuilder setKind(String kind) => _with(() => _kind = kind);
  MessageBuilder setSource(String source) => _with(() => _source = source);
  MessageBuilder setDestination(String destination) =>
      _with(() => _destination = destination);
  MessageBuilder setKeyId(String keyId) => _with(() => _keyId = keyId);
  MessageBuilder setLocalKeyId(String? localKeyId) =>
      _with(() => _localKeyId = localKeyId);
  MessageBuilder setValue(String value) => _with(() => _value = value);
  MessageBuilder setVersion(String version) => _with(() => _version = version);
  MessageBuilder setIntegrityHash(String? integrityHash) =>
      _with(() => _integrityHash = integrityHash);
  MessageBuilder setSize(int? size) => _with(() => _size = size);
  MessageBuilder setContentType(String? contentType) =>
      _with(() => _contentType = contentType);
  MessageBuilder setFlags(List<String>? flags) => _with(() => _flags = flags);
  MessageBuilder setSequence(int? sequence) =>
      _with(() => _sequence = sequence);
  MessageBuilder setCreated(DateTime created) =>
      _with(() => _created = created);
  MessageBuilder setApplicationVersion(String applicationVersion) =>
      _with(() => _applicationVersion = applicationVersion);
  MessageBuilder setPosition(int? position) =>
      _with(() => _position = position);
  MessageBuilder setLanguage(String? language) =>
      _with(() => _language = language);

  // --- Build method with validation ---

  Message build() {
    return Message._(
      id: _requireNonEmpty(_id, 'id'),
      kind: _requireNonEmpty(_kind, 'kind'),
      source: _requireNonEmpty(_source, 'source'),
      destination: _requireNonEmpty(_destination, 'destination'),
      keyId: _requireNonEmpty(_keyId, 'keyId'),
      localKeyId: _localKeyId,
      value: _requireNonEmpty(_value, 'value'),
      version: _requireNonEmpty(_version, 'version'),
      integrityHash: _integrityHash,
      size: _size,
      contentType: _contentType,
      flags: _flags,
      sequence: _sequence, // Optional: server-assigned
      created: _created ?? _missing('created'),
      applicationVersion:
          _requireNonEmpty(_applicationVersion, 'applicationVersion'),
      position: _position, // Optional: server-assigned
      language: _language, // Optional: may be unknown
    );
  }

  // --- Internal helpers ---

  MessageBuilder _with(void Function() updater) {
    updater();
    return this;
  }

  String _requireNonEmpty(String? value, String fieldName) {
    if (value == null || value.trim().isEmpty) {
      throw StateError("Field '$fieldName' must not be empty.");
    }
    return value;
  }

  Never _missing(String field) =>
      throw StateError("Missing required field: $field");
}
